### ISSUE TITLE
Locale is not correctly updated after changing language

### ISSUE THREAD

**Issue by southrop** [MalitsPlus/ShizuruNotes#14]
While implementing English translation in a fork, I found that changing the language in the app does not correctly update the locale of the app for all resources. It appears that strings that are used in program code correctly use the locale set in the settings, but the strings used in XML seem to use the device's default locale/language.

I had a look at the LocaleManager code and couldn't really find the issue myself, but from reading [this](https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758) article, I think it might be because XML and Kotlin are using different `Resources` internally.

Here are some screenshots demonstrating this issue. These screenshots are taken from an Android emulator running Android Q (API 29) in English but with app language set to Japanese. As you can see, some parts of the app are shown in English (parts that are set in XML), but others are in Japanese (parts set in Kotlin).

<img src="https://user-images.githubusercontent.com/2568167/82158859-7eb51f80-98c5-11ea-8c5a-9f08accdca4a.png" width="200"> <img src="https://user-images.githubusercontent.com/2568167/82158860-7fe64c80-98c5-11ea-9a96-b823f68ea16d.png" width="200"> <img src="https://user-images.githubusercontent.com/2568167/82158863-807ee300-98c5-11ea-87d4-50b358495e5d.png" width="200">
(click for full size image)

**Comment by MalitsPlus** [comment]
I faced the same issue at first until add a line that forced to relaunch application after change the language. 
My conclusion is just opposite to yours, strings those are used in code will not correctly update but 
those are used in xml will. 
The reason for this issue is, `I18N` use a static `Application` which is assigned immediately after application launch as the strings source. If you change the locale without relaunching application, `I18N` will get strings from the expired `Application` so you will get the strings those are assigned in the previous locale xml. Alternatively, you can use `Activity` as strings source instead of `Application` in ShizuruNotes because it is a single-activity architecture application, relaunching is unnecessary in this way despite the memory leak warning.

**Comment by southrop** [comment]
I did a bit more reading into this issue, and it turns out it's a bug in appcompat v1.1.0 ([Google Issue Tracker](https://issuetracker.google.com/issues/140602653) reference). I tried updating it to v1.2.0-rc01 without any other source changes to see if it made a difference and it seems fixes the issue entirely.

<img src="https://user-images.githubusercontent.com/2568167/82341238-1f711f80-9a2b-11ea-9843-2fdbcce3d9b5.png" width="200" /> <img src="https://user-images.githubusercontent.com/2568167/82341243-20a24c80-9a2b-11ea-9d0a-884642d68e89.png" width="200" /> <img src="https://user-images.githubusercontent.com/2568167/82341244-213ae300-9a2b-11ea-9f64-e1a48120138e.png" width="200" /> 


As this isn't an bug with the code in this project, I'm going to close this issue. Sorry for the fuss!
