### ISSUE TITLE
Skill action的生效时间

### ISSUE THREAD

**Issue by acaly** [MalitsPlus/ShizuruNotes#23]
最近发现一些要查action生效时间的需求（比如伊莉亚的无影爪），这部分数据应该是在prefabs里，请问有没有相关的计划？

另外我自己在找数据的时候没有找到普攻的生效时间（prefabs里```ActionId```为0的效果的时间和实测不符），也想请教一下有没有什么思路。

感谢！

**Comment by HerDataSam** [comment]
Hi, I am also seeking the effective skill time as you did. I am also developing the KR version ShizuruNotes, KasumiNotes. 

You can ignore the `data` in the `ActionParametersOnPrefab` when `Visible` is 0. It seems that those parameters are discarded at the development level (I am not sure). 

Like your example, Iriya, her `Skill 1` has three actions, 104400201~3. The first and third actions are attack skills `ActionType: 1`, the second one is a buff skill, `ActionType: 10`, you may match those skills with DB. You don't need to consider other actions which number is 0.
If `普攻` is correctly translated into `normal attack`, it seems that it lies in the `ActionParametersOnPrefab` on `Attack` section in the same JSON file. 

But, I can say that there are some exceptions like `真琴`, Makoto's second skill. In the prefab, debuff time starts at 0.8 sec, while real execution time is 1.0 sec. I have checked this using several videos frame by frame. 
One more exception: `FireArm` attack. (for example, 凱留（夏日）) To calculate the exact time, you need to consider its speed and distance. 

That's why I gave up applying effective action time. I will re-consider it if there is a breakthrough. 

Thanks.

**Comment by MalitsPlus** [comment]
Just like HerDataSam said above, prefabs data is confused and troublesome to resolve. 
其实之前有考虑过把prefabs里的具体生效时间和攻击hit次数等数据搞出来，后来想了下只是对于查看技能效果的话这些数据没啥太大必要就放弃了，目前也暂时没有相关计划。
不过对于你说的普攻时间我倒是有点头绪。逆向出来的代码里面有个`BattleDefine`类，里面有叫做`WEAPON_HIT_DELAY_DIC`和`WEAPON_EFFECT_DELAY_DIC`的字典，看上去像是定义了使用各种武器的角色普攻的击中时间，如果prefabs里没有的话有可能是在那里（我云的没有具体研究过

**Comment by acaly** [comment]
Thanks @HerDataSam. 

For Makoto, I have also checked frame by frame. The debuff starts at frame 48 as the prefab indicates (0.8 sec). For the total action time of the skill, we should look at the spine animation (https://redive.estertion.win/spine). For that skill specifically, the animation is 1.2333 sec, which converts to 74 frames. I found that there is 1 additional frame before the next cast time starts (probably the delay in the code to check whether the animation has stopped), so it's 75 frames in total. I think this skill is not exceptional. For some skills (mainly UBs) there is a ```SlowEffect``` that needs to be considered.

<br/>

> 不过对于你说的普攻时间我倒是有点头绪。逆向出来的代码里面有个`BattleDefine`类，里面有叫做`WEAPON_HIT_DELAY_DIC`和`WEAPON_EFFECT_DELAY_DIC`的字典，看上去像是定义了使用各种武器的角色普攻的击中时间，如果prefabs里没有的话有可能是在那里（我云的没有具体研究过

很有可能，我测试真琴的普攻在30帧生效，prefabs里是0.4秒，差了0.1秒。宫子的普攻在27帧生效，prefabs里是0.3秒，差了0.15秒。我没有逆向的代码，能不能帮忙查一下看看有没有可能符合？

另一个问题就是法师的普攻了，那些子弹的时间比较麻烦，应该是固定水平方向或移动方向的速度。不过这个和数据的显示也没有什么关系了。

**Comment by MalitsPlus** [comment]
查了一下： 
makoto的武器应该是双手剑（LONGSWORD），代码里定义的浮点数是0.47f，有一点误差 
miyako的武器是斧（AX），定义的浮点数是0.45f，正好吻合你给的27帧 

关于弹丸的飞行时间，我粗略扫了一下create prefab的部分，没有找到与距离和速度相关的内容，会不会就是一个固定值？

**Comment by HerDataSam** [comment]
> 关于弹丸的飞行时间，我粗略扫了一下create prefab的部分，没有找到与距离和速度相关的内容，会不会就是一个固定值？

I don't think the flying time is fixed. You may consider the second skill of `Kyaru (summer) / 凱留（夏日）`, which is one of the slowest fire. This skill has a different effect time in the main quest rather than the Clan Battle boss. It usually flies from bone to bone, and each fire has its own `MoveRate`. You can refer `FirearmCtrl`. 

And thanks @acaly  
Maybe my player or recorder was wrong. If the effect time always follows the time in the prefab, the only thing we need to consider is `Firearm`.

**Comment by acaly** [comment]
感谢

> makoto的武器应该是双手剑（LONGSWORD），代码里定义的浮点数是0.47f，有一点误差
> miyako的武器是斧（AX），定义的浮点数是0.45f，正好吻合你给的27帧

有可能，真琴的时间我有点不太确定是29还是30。0.47秒是28.2帧，可能实际是29帧。如果每种武器的时间是固定的话那也算是个好消息，我可以再去看看其他的角色。（之前没意识到，看了下spine那边，同武器原来都是完全一样的动作。）

**Comment by MalitsPlus** [comment]
> I don't think the flying time is fixed. You may consider the second skill of `Kyaru (summer) / 凱留（夏日）`, which is one of the slowest fire. This skill has a different effect time in the main quest rather than the Clan Battle boss. It usually flies from bone to bone, and each fire has its own `MoveRate`. You can refer `FirearmCtrl`.

Thanks, you are right. I did find the stuff related to projectile in `Firearm` just as you said. 
But it seems there are soooooo many factors should be considered and I decided to give up figuring it out...
